export const validNames = [
    "Zhuldyz",
    "zhuldyz",
    "Zhuldyzzym",
    "zhuldyzzym",
    "Zhuldyzka",
    "zhuldyzka",
    "ZHULDYZ",
    "ZHULDYZZYM",
    "ZHULDYZKA",
    "ZhUlDyZ",
    "ZHUldyZ",
    "ZhuLdyZkA",
    "ZhUlDyZzYm",
    "Zhuldyzzum",
    "Zhuldyyzzym",
    "ZhuIdyz",
    "Zhuldyzkaa",
    "Zuldiz",
    "Zhuldizym",
];
export const bigPages = ["/gift", "/memory", "/questions", "/admin"];
